<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BookingsEditHistory extends Model
{
    protected $fillable = [
   'id',
   'booking_id',
   'website_id',
  'bk_ref',
  'customer_id',
  'country_id',
  'airport_id',
  'bk_date',
  'bk_from_date',
  'bk_to_date',
  'bk_days',
  'bk_hours',
  'bk_mins',
  'currency_id',
  'bk_gross_price',
  'bk_discount_coupon',
  'bk_discount_value',
  'bk_discount_amount',
  'bk_access_fee',
  'bk_vat_value',
  'bk_vat_amount',
  'bk_online_fee_value',
  'bk_online_fee_amount',
  'bk_booking_fee',
  'bk_total_amount',
  'bk_discount_offer_coupon',
  'bk_discount_offer_value',
  'bk_discount_offer_amount',
  'bk_final_amount',
  'bk_ou_fl_nu',
  'bk_ou_te',
  'bk_re_fl_nu',
  'bk_re_te',
  'bk_re_nu',
  'bk_ve_ma',
  'bk_ve_mo',
  'bk_ve_co',
  'bk_ve_do_dt',
  'bk_ve_pu_dt',
  'bk_nop',
  'bk_note',
  'bk_agtnote',
  'bk_fagtnote',
  'bk_payment_method',
  'bk_payment_status',
  'bk_status',
  'bk_vip',
  'agent_id',
  'fwd_agt_id',
  'bk_is_del',
  'bk_email_flag',
  'bk_print_flag',
  'carwash_in_and_out',
  'carwash_out_only',
  'carwash_in_only',
  'carwash_spray_only',
  'not_working_hours',
  'service_id',
  'checkout_status',
  'checkin_status',
'bk_amount_b4_update',
'bk_days_b4_update',
'bk_dates_b4_updat'
      ];
}
